# +-----------------------------------------------------
# |         SPRING LOGGIN CONFIG
# +-----------------------------------------------------
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG    
    co.com.alfaseguros: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# +-----------------------------------------------------
# |         ALFA PARAMS
# +-----------------------------------------------------

cloud:
  aws:
    region:
      static: ${REGION:us-east-2}
      auto: false

alfa:
  props:
    zone-time: America/Bogota
  services:
    mediatorosb:
      port: 7060      
      url:
        setrecordregistryqueuemessage: http://${DNS_LB:localhost}:${alfa.services.mediatorosb.port}/mediatorosb/api/v1/setRecordRegistryQueueMessage
  queues:
    auditinpolicyquery:
      name: ${NAME_QUEUES_POLICY_QUERY:audit-in-policy-query}
    auditinpaymentregistry:
      name: ${NAME_QUEUES_PAYMENT_REGISTRY:audit-in-payment-registry}