package co.com.alfaseguros.events.domain.entities;


import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;

@Getter
@Setter
@DynamoDbBean
@DynamoDBTable(tableName = "applicationlog")
public class ApplicationLog{
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "userName")
	private String userName ;
	
	@DynamoDBAttribute(attributeName = "detail")
	private List<Detail> detail;
	
	@DynamoDBAttribute(attributeName = "dateTime")
	private String dateTime;
	
	@DynamoDBAttribute(attributeName = "ip")
	private String ip;
	
	@DynamoDBAttribute(attributeName = "channel")
	private String channel;

}
