# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8091
  servlet:
    context-path: /
    session:
      cookie:
        name: UISESSION    
          
# +-----------------------------------------------------
# |         SPRING CONFIG
# +-----------------------------------------------------
spring:
  application:
    name: alfa-events
  profiles:
    active: "@activatedProperties@"